// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Nunito_Sans, Sora } from 'next/font/google';
import { Container } from '@/components/ui/Container/Container';
import './globals.css';

const nunito = Nunito_Sans({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-nunito',
  display: 'swap',
});

const sora = Sora({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-sora',
  display: 'swap',
});
// Шрифт Sora НЕ підтримує кирилицю в Google Fonts

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className={`${geistSans.variable} ${geistMono.variable}`}>
    //     {children}
    //   </body>
    // </html>
    <html lang="uk" className={`${nunito.variable} ${sora.variable}`}>
      <body>
        <header>
          <Container>
            <h1>HEADER</h1>
          </Container>
        </header>
        <main>{children}</main>
        <footer>
          <Container>
            <h1>FOOTER</h1>
          </Container>
        </footer>
      </body>
    </html>
  );
}
