// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Container } from "@/components/ui/Container/Container";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className={`${geistSans.variable} ${geistMono.variable}`}>
    //     {children}
    //   </body>
    // </html>
    <html lang="en">
      <body>
        <header>
          <Container>
            <h1>HEADER</h1>
          </Container>
        </header>
        <main>{children}</main>
        <footer>
          <Container>
            <h1>FOOTER</h1>
          </Container>
        </footer>
      </body>
    </html>
  );
}
